added HW for 3 lecture
415816/js_HW pull request #1
Opened 2024-05-27 20:44 UTC by 415816

added HW for 3 lecture

2024-05-27 22:01 UTC, lenanova commented on lec_3_HW/task_2.js
В строке 5 проверь формулу D.
Также в задаче есть подсказка, сколько корней должо получиться.
![image](https://github.com/415816/js_HW/assets/88866011/f99272fb-ec87-4c9e-a666-ba3c244d7cf7)

2024-05-28 10:51 UTC, VladimirLQA requested changes

2024-05-28 10:51 UTC, VladimirLQA commented on lec_3_HW/task_3.js
> +    let third = "" + n + n + n;
Use `const`

2024-05-28 10:51 UTC, VladimirLQA commented on lec_3_HW/task_2.js
> +        return (result += `, x2 = ${x}`);
```suggestion
    let D = b ** 2 - 4 * a * c;
    if (D > 0) {
        x = ((-b + Math.sqrt(D)) / 2) * a;
        result = `x1 = ${x}`;
        x = ((-b - Math.sqrt(D)) / 2) * a;
        return (result += `, x2 = ${x}`);
```

2024-05-28 18:03 UTC, 415816 commented on lec_3_HW/task_2.js
Принято и скорректировано, спасибо

2024-05-28 18:04 UTC, 415816 commented on lec_3_HW/task_3.js
> +    let third = "" + n + n + n;
ок, принято

2024-05-28 18:12 UTC, 415816 commented on lec_3_HW/task_2.js
> +        return (result += `, x2 = ${x}`);
Формула скорректирована.

2024-05-28 18:52 UTC, VladimirLQA approved these changes

2024-05-28 19:09 UTC, merged