added 5th HW
415816/js_HW pull request #3
Opened 2024-06-01 18:16 UTC by 415816

2024-06-01 22:26 UTC, anatoly-karpovich requested changes

2024-06-01 22:26 UTC, anatoly-karpovich commented on lec_5_HW/task_2.js
> +const currency = (value, units) => {
Нет:) ты не извне получаешь формат в который надо перевести, а надо циклом делить на 1024 до упора, и определять по ходу какой стал формат)

2024-06-02 03:53 UTC, 415816 commented on lec_5_HW/task_2.js
> +const currency = (value, units) => {
Ааа, ок, поправил)

2024-06-02 03:57 UTC, anatoly-karpovich approved these changes

2024-06-02 11:46 UTC, merged